[package]
name = "stevio_code"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
clap_complete = "4.5.52"
git2 = "0.20.2"
limbo = "0.0.20"
serde = "1.0.219"
thiserror = "2.0.12"
walkdir = "2"
